#!/usr/bin/env python
"""
Webserver to serve the reply form.
"""
import os
import time

import flask

app = flask.Flask(__name__)

REPLY_DIRECTORY = os.path.expanduser('~/.irssi/reply-data')

FORM = """\
<html>
    <title>{target} Reply</title>
    <form method="post">
        <label>{target}</label>
        <input type="text" name="reply">
        <input type="submit" value="Reply">
    </form>
</html>
"""


@app.route('/success')
def success():
    return "Reply sent!"


@app.route('/<target>', methods=['GET', 'POST'])
def handle_reply(target):
    if flask.request.method == 'POST':
        reply = flask.request.form['reply']

        # Write our reply to reply-data directory which is the communication
        # channel between the webserver and the reply.pl irssi plugin
        if not os.path.exists(REPLY_DIRECTORY):
            os.makedirs(REPLY_DIRECTORY)
        path = os.path.join(REPLY_DIRECTORY, str(time.time()))
        with open(path, 'w') as f:
            f.write(" ".join([target, reply]) + '\n')

        return flask.redirect(flask.url_for('success'))
    else:
        return FORM.format(target=target)


if __name__ == '__main__':
    app.run(host='0.0.0.0', debug=True)
